project_id = "kikanqxtcsrourtqbqpy"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[graphql]
enabled = true
port = 54325
max_depth = 12
max_rows = 1000

[inbucket]
enabled = true
port = 54324
sender_name = "Supabase"
smtp_port = 54325
pop3_port = 54326

[realtime]
enabled = true
port = 54323
ip_version = "IPv4"

[studio]
enabled = true
port = 54326
api_url = "http://localhost:54321"

[auth]
enabled = true
port = 54327
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[edge_runtime]
enabled = true
port = 54328
inspector_port = 54329

[functions.generate-document]
verify_jwt = true