ALTER TABLE usuarios 
  ADD COLUMN IF NOT EXISTS cargo VARCHAR(120),
  ADD COLUMN IF NOT EXISTS departamento VARCHAR(120),
  ADD COLUMN IF NOT EXISTS bio TEXT,
  ADD COLUMN IF NOT EXISTS telefone VARCHAR(40);

