version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: movemarias_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-assist_move_assist}
      POSTGRES_USER: ${POSTGRES_USER:-assistmove}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-assistmove123}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - movemarias_network

  redis:
    image: redis:7
    container_name: movemarias_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - movemarias_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: movemarias_backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOST=0.0.0.0
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=assist_move_assist
      - POSTGRES_USER=assistmove
      - POSTGRES_PASSWORD=assistmove123
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=assist-move-assist-dev-secret-key-2025
      - JWT_EXPIRES_IN=24h
      - CORS_ORIGIN=http://localhost:5173
      - FRONTEND_URL=http://localhost:5173
      - ENABLE_WS=true
      - SUPERADMIN_NAME=Bruno Admin
      - SUPERADMIN_EMAIL=bruno@move.com
      - SUPERADMIN_PASSWORD=15002031
      - ADMIN_NAME=Administrador
      - ADMIN_EMAIL=admin@movemarias.com
      - ADMIN_PASSWORD=movemarias123
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - movemarias_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: movemarias_frontend
    ports:
      - "5173:5173"
    environment:
      # Container talks to backend by service name on the bridge network
      - VITE_API_URL=http://backend:3000/api
      - VITE_API_BASE_URL=http://backend:3000/api
    depends_on:
      - backend
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - movemarias_network

volumes:
  postgres_data:
  redis_data:

networks:
  movemarias_network:
    driver: bridge
