version: '3.9'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: movemarias
      POSTGRES_USER: movemarias
      POSTGRES_PASSWORD: change-me
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.production
    depends_on:
      - postgres
      - redis
    environment:
      NODE_ENV: production
      PORT: 3000
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: movemarias
      POSTGRES_USER: movemarias
      POSTGRES_PASSWORD: change-me
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: please-change-in-prod
      ENABLE_WS: "true"
      CORS_ORIGIN: http://localhost:4173
    ports:
      - "3000:3000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.production
    depends_on:
      - backend
    environment:
      VITE_API_BASE_URL: http://localhost:3000/api
    ports:
      - "4173:4173"

volumes:
  pgdata:
  redisdata:

