name: Deploy to VPS

on:
  workflow_dispatch:

env:
  VPS_PORT: ${{ vars.VPS_PORT || 22 }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.7.3
        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ vars.VPS_USER || 'root' }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ env.VPS_PORT }}
          script: |
            cd ${{ vars.DEPLOY_PATH || '/opt/assist-move-assist' }}
            docker compose pull && docker compose up -d --remove-orphans
