name: Permissions Smoke
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}
jobs:
  smoke:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: movemarias
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
      redis:
        image: redis:7
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install backend deps
        run: |
          cd backend
          npm ci
      - name: Create .env
        run: |
          cat > backend/.env << 'ENV'
          NODE_ENV=development
          PORT=3000
          POSTGRES_HOST=localhost
          POSTGRES_PORT=5432
          POSTGRES_DB=movemarias
          POSTGRES_USER=postgres
          POSTGRES_PASSWORD=postgres
          JWT_SECRET=ci-secret
          ENABLE_WS=false
          ENV
      - name: Migrate (node fallback)
        run: |
          cd backend
          npm run migrate:node
      - name: Build backend
        run: |
          cd backend
          npm run build
      - name: Start API
        run: |
          cd backend
          nohup npm start &
          for i in {1..30}; do curl -sf http://localhost:3000/api/health && break || sleep 2; done
      - name: Run config smoke
        env:
          API_BASE: http://localhost:3000/api
          SUPER_EMAIL: bruno@move.com
          SUPER_PASS: 15002031
        run: |
          cd backend
          npm run smoke:config
