name: Permissions Smoke
on:
  push:
    branches: [main]
  workflow_dispatch: {}
jobs:
  smoke:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: movemarias
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
      redis:
        image: redis:7
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install backend deps
        run: |
          cd apps/backend
          npm ci
      - name: Create .env
        run: |
          cat > apps/backend/.env << 'ENV'
          NODE_ENV=development
          PORT=3000
          POSTGRES_HOST=localhost
          POSTGRES_PORT=5432
          POSTGRES_DB=movemarias
          POSTGRES_USER=postgres
          POSTGRES_PASSWORD=postgres
          JWT_SECRET=ci-secret
          ENABLE_WS=false
          SUPERADMIN_EMAIL=bruno@move.com
          SUPERADMIN_PASSWORD=15002031
          ENV
      - name: Bootstrap migration compat tables
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DB: movemarias
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        run: |
          cd apps/backend
          node - <<'NODE'
          const { Client } = require('pg');
          const client = new Client({
            host: process.env.POSTGRES_HOST || 'localhost',
            port: parseInt(process.env.POSTGRES_PORT || '5432', 10),
            database: process.env.POSTGRES_DB || 'movemarias',
            user: process.env.POSTGRES_USER || 'postgres',
            password: process.env.POSTGRES_PASSWORD || 'postgres',
            ssl: false,
          });
          (async () => {
            await client.connect();
            try {
              await client.query(`CREATE TABLE IF NOT EXISTS migrations (
                id SERIAL PRIMARY KEY,
                name VARCHAR(255) NOT NULL UNIQUE,
                applied_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
              );`);
              await client.query(`
                CREATE TABLE IF NOT EXISTS migration_log (id SERIAL PRIMARY KEY);
                DO $$
                BEGIN
                  IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name='migration_log' AND column_name='migration_name'
                  ) THEN
                    ALTER TABLE migration_log ADD COLUMN migration_name VARCHAR(255);
                  END IF;
                  IF NOT EXISTS (
                    SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'uq_migration_log_migration_name'
                  ) THEN
                    CREATE UNIQUE INDEX uq_migration_log_migration_name ON migration_log (migration_name);
                  END IF;
                  IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name='migration_log' AND column_name='executed_at'
                  ) THEN
                    ALTER TABLE migration_log ADD COLUMN executed_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;
                  END IF;
                  IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name='migration_log' AND column_name='description'
                  ) THEN
                    ALTER TABLE migration_log ADD COLUMN description TEXT;
                  END IF;
                END $$;
              `);
            } finally {
              await client.end();
            }
          })().catch((e) => { console.error(e); process.exit(1); });
          NODE
      - name: Migrate (node fallback)
        run: |
          cd apps/backend
          npm run migrate:node
      - name: Build backend
        run: |
          cd apps/backend
          npm run build
      - name: Start API
        run: |
          cd apps/backend
          nohup npm start &
          for i in {1..30}; do curl -sf http://localhost:3000/api/health && break || sleep 2; done
      - name: Run config smoke
        env:
          API_BASE: http://localhost:3000/api
          SUPER_EMAIL: bruno@move.com
          SUPER_PASS: 15002031
        run: |
          cd apps/backend
          npm run smoke:config
      - name: Run reports smoke
        env:
          API_BASE: http://localhost:3000/api
          SUPER_EMAIL: bruno@move.com
          SUPER_PASS: 15002031
        run: |
          cd apps/backend
          npm run smoke:reports
